/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  ModWorkspace,
  PackageDiagnostic,
  AIBehaviorScript,
  JobDef,
  PatchBlock,
  TFile,
  WareDef
} from '../types';
import { validateContract } from './contractGlue';
import { analyzeLuaFiles } from './luaStaticAnalysis';
import { DOMParser as XmlDOMParser } from '@xmldom/xmldom';

/**
 * P4 guard: is `content` a well-formed XML fragment? Wrap it as a single <root> (same
 * shape the XML-Patch "Applied Preview" uses) and parse-check it. Matches xpathSynth's
 * xmldom `onError` pattern so it works identically in the browser and in Node. An empty
 * body is treated as valid (self-closing intent).
 */
function isWellFormedXmlFragment(content: string): boolean {
  const raw = (content || '').trim();
  if (!raw) return true;
  let fatal = false;
  try {
    new XmlDOMParser({
      onError: (level: string) => { if (level === 'fatalError') fatal = true; },
    }).parseFromString(`<root>${raw}</root>`, 'text/xml');
  } catch { fatal = true; }
  return !fatal;
}

interface TFileNameInput {
  fileName?: string;
  languageId?: string;
}

export const toSafeModId = (name: string): string => {
  const safe = name
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
  return safe || 'x4_md_studio_mod';
};

/**
 * Workspace version → X4 content.xml version integer (X4 shows 100 as "1.00").
 * Audit #1 (2026-07-10): format-aware. A PURE INTEGER is treated as ALREADY being the X4
 * version and passes through untouched ("100" → "100"; the old blind ×100 turned it into
 * "10000" — a shipped-artifact corruption a modder using X4's own convention would hit).
 * Dotted versions keep the EXACT previous behavior (parseFloat×100: "1.0.0" → "100",
 * "1.2" → "120"), so every existing semver-authored mod compiles to the same number.
 */
export const toContentVersion = (value: string): string => {
  const raw = String(value || '').trim();
  if (/^\d+$/.test(raw)) return String(Math.max(1, parseInt(raw, 10))); // already X4 format
  const normalized = raw.match(/^\d+(?:\.\d+)?/)?.[0];
  const numericVersion = normalized ? Number.parseFloat(normalized) : 1;
  const contentVersion = Number.isFinite(numericVersion)
    ? Math.round(numericVersion * 100)
    : 100;

  return String(Math.max(1, contentVersion));
};

export const escapeXmlAttr = (str: string): string => {
  return (str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
};

export const escapeXmlText = (str: string): string => {
  return (str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
};

export const toTFileName = (file: TFileNameInput): string => {
  const explicitName = String(file?.fileName || '').trim();
  if (explicitName) {
    const match = explicitName.match(/^(.+?)-[lL](\d+)\.xml$/);
    if (match) {
      return `${match[1]}-l${match[2].padStart(3, '0')}.xml`;
    }
    return explicitName;
  }

  const languageId = String(file?.languageId || '44').replace(/\D/g, '') || '44';
  return `0001-l${languageId.padStart(3, '0')}.xml`;
};

export const generateContentXML = (modId: string, workspace: ModWorkspace): string => {
  const today = new Date().toISOString().slice(0, 10);
  const displayName = workspace.name || modId;
  const description = workspace.description || 'Generated by X4 Forge';
  const author = workspace.author || 'X4 Forge';
  // Emit declared dependencies so they survive regeneration (previously dropped → the mod
  // silently no-op'd APIs in-game and the dependency analyzer kept warning).
  const depLines = (((workspace as any).dependencies || []) as Array<{ id?: string; version?: string; optional?: boolean }>)
    .filter(d => d && d.id)
    .map(d => {
      const attrs = [`id="${escapeXmlAttr(d.id!)}"`];
      if (d.version) attrs.push(`version="${escapeXmlAttr(d.version)}"`);
      if (d.optional) attrs.push(`optional="true"`);
      return `  <dependency ${attrs.join(' ')} />`;
    });
  return `<?xml version="1.0" encoding="utf-8"?>\n<content id="${escapeXmlAttr(modId)}" name="${escapeXmlAttr(displayName)}" description="${escapeXmlAttr(description)}" author="${escapeXmlAttr(author)}" version="${toContentVersion(workspace.version)}" date="${today}" save="0" enabled="1">\n  <text language="44" name="${escapeXmlAttr(displayName)}" description="${escapeXmlAttr(description)}" author="${escapeXmlAttr(author)}" />\n${depLines.length ? depLines.join('\n') + '\n' : ''}</content>\n`;
};

/**
 * #65 — provenance-aware aiscript namespacing. Returns the FINAL aiscript name for
 * export: a bare authored name is prefixed `<modId>.<name>` (so two studio mods don't
 * ship colliding generic filenames); a name that already carries the modId prefix — or
 * any name marked final via `alreadyNamespaced` (e.g. an imported foreign-namespaced
 * script) — is returned unchanged. Pure + idempotent: f(f(x)) === f(x).
 */
export const namespaceAiScriptName = (name: string, modId: string, alreadyNamespaced = false): string => {
  const n = (name || '').trim();
  if (!n || !modId) return n;
  const prefix = `${modId}.`;
  if (alreadyNamespaced || n.startsWith(prefix)) return n;
  return `${prefix}${n}`;
};

export const compileScriptToXML = (script: AIBehaviorScript): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<aiscript name="${escapeXmlAttr(script.name)}" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="aiscripts.xsd">\n`;
  xml += `  <!-- X4 Foundations Autopilot & Task Script Behavior -->\n`;
  xml += `  <!-- Generated visually using X4 Forge Behaviors Suite -->\n`;
  xml += `  <params>\n`;
  (script.params || []).forEach((p) => {
    xml += `    <param name="${escapeXmlAttr(p.name)}" type="${escapeXmlAttr(p.type)}" default="${escapeXmlAttr(p.defaultValue)}" comment="${escapeXmlAttr(p.comment)}" />\n`;
  });
  xml += `  </params>\n`;

  if (script.interrupts && script.interrupts.length > 0) {
    xml += `  <interrupts>\n`;
    script.interrupts.forEach((int) => {
      xml += `    <handler event="${escapeXmlAttr(int.event)}">\n`;
      xml += `      <actions>\n`;
      if (int.action === 'flee') {
        xml += `        <run_script name="'move.flee'" />\n`;
      } else if (int.action === 'dock_at_safety') {
        xml += `        <run_script name="'move.dockat'" />\n`;
      } else {
        xml += `        <write_to_logbook text="'Interrupt event fired: ${escapeXmlAttr(int.event)}'" />\n`;
      }
      xml += `      </actions>\n`;
      xml += `    </handler>\n`;
    });
    xml += `  </interrupts>\n`;
  }

  xml += `  <attention min="${escapeXmlAttr(script.attentionLevel || 'low')}">\n`;
  xml += `    <actions>\n`;
  xml += `      <label name="start" />\n`;

  (script.actions || []).forEach((act) => {
    xml += `      <!-- Action: ${escapeXmlText(act.label)} -->\n`;
    switch (act.command) {
      case 'move_to':
        xml += `      <move_to object="this.ship" destination="${escapeXmlAttr(act.properties.destination || '$target')}" forceposition="false" finishonfound="true">\n`;
        xml += `        <interrupt_after_time time="10s" />\n`;
        xml += `      </move_to>\n`;
        break;
      case 'flee':
        xml += `      <run_script name="'move.flee'" />\n`;
        break;
      case 'shoot':
        xml += `      <shoot_at object="this.ship" target="${escapeXmlAttr(act.properties.target || '$enemy')}" turretmode="attackhostile" />\n`;
        break;
      case 'dock_at':
        xml += `      <dock_at object="this.ship" station="${escapeXmlAttr(act.properties.station || '$station')}" />\n`;
        break;
      case 'wait':
        if (act.properties.exact) {
          xml += `      <wait exact="${escapeXmlAttr(act.properties.exact)}" />\n`;
        } else {
          xml += `      <wait min="${escapeXmlAttr(act.properties.min || '2s')}" max="${escapeXmlAttr(act.properties.max || '10s')}" />\n`;
        }
        break;
      case 'find_objects':
        xml += `      <find_object name="$targets" class="class.${escapeXmlAttr(act.properties.class || 'ship')}" space="player.sector" multiple="true" />\n`;
        break;
      case 'custom_xml':
        xml += `      ${act.properties.rawXml || '<!-- custom nodes -->'}\n`;
        break;
    }
  });

  xml += `    </actions>\n`;
  xml += `  </attention>\n`;
  xml += `</aiscript>`;
  return xml;
};

export const compileWaresXML = (wares: WareDef[]): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<diff>\n`;
  xml += `  <!-- XML Diff Patch adding to core wares database file: libraries/wares.xml -->\n`;
  xml += `  <add sel="/wares">\n`;
  wares.forEach((item) => {
    const tagsAttr = item.tags ? ` tags="${escapeXmlAttr(item.tags)}"` : '';
    const productionMethod = item.productionMethod || 'default';
    const productionNameAttr = item.productionName ? ` name="${escapeXmlAttr(item.productionName)}"` : '';
    const primaryWares = Array.isArray(item.primaryWares)
      ? item.primaryWares.filter((ware) => String(ware?.ware || '').trim() && Number(ware?.amount) > 0)
      : [];

    xml += `    <ware id="${escapeXmlAttr(item.id)}" name="${escapeXmlAttr(item.name)}" description="${escapeXmlAttr(item.description)}" transport="${escapeXmlAttr(item.transport)}" volume="${item.volume}"${tagsAttr}>\n`;
    xml += `      <price min="${item.minPrice}" average="${item.avgPrice}" max="${item.maxPrice}" />\n`;
    xml += `      <production time="${item.prodTime}" amount="${item.prodAmount}" method="${escapeXmlAttr(productionMethod)}"${productionNameAttr}`;
    if (primaryWares.length === 0) {
      xml += ` />\n`;
    } else {
      xml += `>\n`;
      xml += `        <primary>\n`;
      primaryWares.forEach((ware) => {
        xml += `          <ware ware="${escapeXmlAttr(ware.ware)}" amount="${escapeXmlAttr(String(ware.amount))}" />\n`;
      });
      xml += `        </primary>\n`;
      xml += `      </production>\n`;
    }
    xml += `    </ware>\n`;
  });
  xml += `  </add>\n`;
  xml += `</diff>`;
  return xml;
};

export const compileJobsXML = (jobs: JobDef[]): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<diff>\n`;
  xml += `  <!-- XML Diff Patch adding new AI pilot squad to core jobs database: libraries/jobs.xml -->\n`;
  xml += `  <add sel="/jobs">\n`;
  jobs.forEach((item) => {
    xml += `    <job id="${escapeXmlAttr(item.id)}" name="${escapeXmlAttr(item.name)}" startactive="true">\n`;
    xml += `      <modifiers rebuild="${item.rebuildOnDestroy ? 'true' : 'false'}" />\n`;
    xml += `      <quota galaxy="${item.galaxyQuota}" sector="${item.sectorQuota}" />\n`;
    xml += `      <expirationtime min="7200" max="14400" />\n`;
    if (item.taskScript) xml += `      <task task="${escapeXmlAttr(item.taskScript)}" />\n`;
    xml += `      <ship macro="${escapeXmlAttr(item.shipMacro)}">\n`;
    xml += `        <select faction="${escapeXmlAttr(item.faction)}" tags="[military, ${escapeXmlAttr(item.shipClass)}]" />\n`;
    xml += `        <owner exact="${escapeXmlAttr(item.faction)}" overridenpc="true" />\n`;
    xml += `      </ship>\n`;
    xml += `    </job>\n`;
  });
  xml += `  </add>\n`;
  xml += `</diff>`;
  return xml;
};

export const compileTFileXML = (file: TFile): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<language id="${escapeXmlAttr(file.languageId)}">\n`;
  (file.pages || []).forEach((page) => {
    const title = page.title ? ` title="${escapeXmlAttr(page.title)}"` : '';
    xml += `  <page id="${escapeXmlAttr(page.id)}"${title}>\n`;
    (page.items || []).forEach((item) => {
      const comment = item.description ? ` <!-- ${escapeXmlText(item.description)} -->` : '';
      xml += `    <t id="${escapeXmlAttr(item.id)}">${escapeXmlText(item.value)}</t>${comment}\n`;
    });
    xml += `  </page>\n`;
  });
  xml += `</language>`;
  return xml;
};

export const compileDiffDocument = (patches: PatchBlock[], targetFile: string): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- XML Diff patch targeting file: "${escapeXmlAttr(targetFile)}" -->\n`;
  xml += `<diff>\n\n`;
  patches.forEach((b) => {
    if (b.note) {
      xml += `  <!-- Patch Note: ${escapeXmlText(b.note)} -->\n`;
    }
    if (b.action === 'remove') {
      xml += `  <remove sel="${escapeXmlAttr(b.sel)}" />\n\n`;
    } else if (b.action === 'add' && b.attrType) {
      // Attribute-level add (T4.2): <add sel="..." type="@attr">value</add>
      xml += `  <add sel="${escapeXmlAttr(b.sel)}" type="${escapeXmlAttr(b.attrType)}">${escapeXmlText((b.content || '').trim())}</add>\n\n`;
    } else if (b.action === 'replace' && b.sel.includes('/@')) {
      // Attribute-value replace: single-line escaped text body
      xml += `  <replace sel="${escapeXmlAttr(b.sel)}">${escapeXmlText((b.content || '').trim())}</replace>\n\n`;
    } else {
      const posAttr = (b.action === 'add' && b.pos) ? ` pos="${escapeXmlAttr(b.pos)}"` : '';
      const raw = (b.content || '').trim();
      // P4: malformed content must NOT compile silently into <diff>. Emit a loud comment
      // marker instead of a broken element (`--` neutralised so it can't close the comment).
      if (!isWellFormedXmlFragment(raw)) {
        xml += `  <!-- INVALID PATCH CONTENT (sel="${escapeXmlAttr(b.sel)}") — fix in the XML Patching workbench before shipping: ${escapeXmlText(raw).replace(/--/g, '- -')} -->\n\n`;
      } else {
        xml += `  <${b.action} sel="${escapeXmlAttr(b.sel)}"${posAttr}>\n`;
        const lines = raw.split('\n').filter((l: string) => l.trim().length > 0);
        lines.forEach((l: string) => {
          xml += `    ${l}\n`;
        });
        xml += `  </${b.action}>\n\n`;
      }
    }
  });
  xml += `</diff>`;
  return xml;
};

/**
 * True when the modeled workspace owns a generated Mission Director document.
 * Source-owned MD passthrough/original files are deliberately excluded: the artifact
 * pipeline preserves those bytes and must not manufacture a second generated script.
 */
export const hasGeneratedMdDomain = (workspace: ModWorkspace): boolean => {
  return (workspace.nodes || []).some(node => node.includeInBuild !== false);
};

/** True when this extension actually contains any Mission Director domain. */
export const hasAnyMdDomain = (workspace: ModWorkspace): boolean => {
  if (hasGeneratedMdDomain(workspace)) return true;
  if (workspace.mdOriginal?.content) return true;
  if ((workspace.originalFiles || []).some(file => file.kind === 'md' || /(^|[\\/])md[\\/].*\.xml$/i.test(file.path))) return true;
  return (workspace.passthroughFiles || []).some(file => /(^|[\\/])md[\\/].*\.xml$/i.test(file.path));
};

/**
 * True when the extension contains deployable authored behavior or data beyond its manifest.
 * An inert legacy MD shell is deliberately not output: data-only mods do not need a placebo cue.
 */
export const hasEffectiveAuthoredOutput = (workspace: ModWorkspace): boolean => {
  const enabled = (key: keyof NonNullable<ModWorkspace['compileSettings']>) => workspace.compileSettings?.[key] !== false;
  const included = <T extends { includeInBuild?: boolean }>(items: T[] | undefined) => (items || []).some(item => item.includeInBuild !== false);
  const sourceMd = [
    ...(workspace.mdOriginal?.content ? [workspace.mdOriginal.content] : []),
    ...(workspace.originalFiles || []).filter(file => file.kind === 'md' || /(^|[\\/])md[\\/].*\.xml$/i.test(file.path)).map(file => file.content),
    ...(workspace.passthroughFiles || []).filter(file => /(^|[\\/])md[\\/].*\.xml$/i.test(file.path)).map(file => file.content || ''),
  ];
  const sourceHasMdEntry = sourceMd.some(content => /<(?:cue|library)\b/.test(content));
  const passthroughHasPayload = (workspace.passthroughFiles || []).some(file => {
    const normalized = file.path.replace(/\\/g, '/').toLowerCase();
    if (normalized === 'content.xml' || /(^|\/)readme(?:\.[^/]*)?$/.test(normalized)) return false;
    if (/^md\/.*\.xml$/.test(normalized)) return /<(?:cue|library)\b/.test(file.content || '');
    return true;
  });
  const modeledOriginalHasPayload = (workspace.originalFiles || []).some(file => {
    if (file.kind === 'content' || file.kind === 'readme') return false;
    if (file.kind === 'md') return /<(?:cue|library)\b/.test(file.content || '');
    return true;
  });

  return (enabled('md') && (hasGeneratedMdDomain(workspace) || sourceHasMdEntry))
    || (enabled('ui') && included(workspace.uiWidgets))
    || (enabled('ai') && included(workspace.aiScripts))
    || (enabled('library') && (included(workspace.wares) || included(workspace.jobs)))
    || (enabled('translations') && included(workspace.tFiles))
    || (enabled('patches') && included(workspace.xmlPatches))
    || !!workspace.customLua?.trim()
    || !!workspace.integrationContract
    || modeledOriginalHasPayload
    || passthroughHasPayload;
};

export const validatePackageReadiness = (workspace: ModWorkspace): PackageDiagnostic[] => {
  const reports: PackageDiagnostic[] = [];
  const modId = toSafeModId(workspace.name);

  if (!workspace.name?.trim()) {
    reports.push({
      severity: 'error',
      message: 'Compiled extension needs a mod name. This becomes the content.xml name and package folder.',
      category: 'egosoft'
    });
  }

  if (!/^[a-z0-9_]+$/.test(modId)) {
    reports.push({
      severity: 'error',
      message: `Compiled extension id "${modId}" must use lowercase letters, numbers, and underscores only.`,
      category: 'egosoft'
    });
  }

  if (!workspace.author?.trim()) {
    reports.push({
      severity: 'warning',
      message: 'Compiled content.xml has no explicit author. Set Mod Meta author before shipping.',
      category: 'egosoft'
    });
  }

  if (!workspace.description?.trim()) {
    reports.push({
      severity: 'warning',
      message: 'Compiled content.xml has no explicit description. Manual users need this in the Extensions menu.',
      category: 'egosoft'
    });
  }

  // Cues can come from the node graph OR from hand-authored MD preserved verbatim. A libraries-only,
  // asset-only, UI-only, or diff-only extension has NO MD domain and therefore needs no cue at all.
  // Only diagnose an entry point when the extension actually contains MD bytes/model nodes.
  const hasGraphCue = workspace.nodes.some(node => node.type === 'cue');
  const sourceMd = [
    ...(workspace.mdOriginal?.content ? [workspace.mdOriginal.content] : []),
    ...(workspace.originalFiles ?? []).filter(file => file.kind === 'md' || /(^|[\\/])md[\\/].*\.xml$/i.test(file.path)).map(file => file.content),
    ...(workspace.passthroughFiles ?? []).filter(file => /(^|[\\/])md[\\/].*\.xml$/i.test(file.path)).map(file => file.content ?? ''),
  ];
  const hasSourceEntryPoint = sourceMd.some(content => /<(?:cue|library)\b/.test(content));
  const hasValidContractMd = !!workspace.integrationContract
    && validateContract(workspace.integrationContract).every(finding => finding.severity !== 'error');
  if (hasGeneratedMdDomain(workspace) && !hasGraphCue && !hasValidContractMd) {
    reports.push({
      severity: 'error',
      code: 'package.md_missing_entrypoint',
      message: 'Modeled Mission Director output has no cue or library entry point. Add real MD logic, or exclude the unused MD nodes from the build.',
      category: 'egosoft'
    });
  } else if (hasAnyMdDomain(workspace) && !hasGraphCue && !hasSourceEntryPoint && !hasValidContractMd) {
    reports.push({
      severity: 'warning',
      code: 'package.md_inert_source',
      message: 'An imported MD file has no cue or library entry point. Data-only XML patch, wares, jobs, and asset mods do not need a cue—remove or exclude the unused MD file instead of adding a placebo cue.',
      category: 'egosoft'
    });
  }

  if (!hasEffectiveAuthoredOutput(workspace)) {
    reports.push({
      severity: 'error',
      code: 'package.empty_extension',
      message: 'The extension has no effective authored output. Add a data patch, ware/job/asset, UI, AI script, translation, Lua file, or real Mission Director cue/library before packaging.',
      category: 'egosoft'
    });
  }

  // P5: custom Lua is written verbatim to ui/<id>_custom.lua regardless of the analyzer, so
  // broken Lua would ship while the package badge stays green. Surface syntax errors here.
  if (workspace.customLua && workspace.customLua.trim()) {
    try {
      const lua = analyzeLuaFiles([{
        rel: `ui/${modId}_custom.lua`,
        text: workspace.customLua,
        source: 'loose',
        sourcePath: `ui/${modId}_custom.lua`,
        extension: { folder: modId, id: modId, name: workspace.name },
      }]);
      for (const f of lua.findings) {
        if (f.severity === 'error') {
          reports.push({
            severity: 'error',
            message: `Custom Lua won't compile (${f.message}). It ships verbatim — fix it before packaging.`,
            category: 'egosoft'
          });
        }
      }
    } catch { /* analyzer unavailable — never block the readiness report */ }
  }

  return reports;
};
