/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * A pure adapter between the accepted X4 UI source bundle and the workspace's
 * existing passthrough-file authority.  This module deliberately does not
 * import the compiler or touch sourceFolder/disk state: callers provide the
 * workspace records and, when needed, the exact generated UI paths.
 */

import type { ModWorkspace, PassthroughFile } from '../types';
import {
  buildX4UiSourceBundle,
  projectX4UiSourceBundle,
  spliceX4UiSourceBundle,
  type X4UiSourceBundle,
  type X4UiSourceBundleProjection,
  type X4UiSourceSplice,
  type X4UiSourceSpliceRefusalReason
} from './x4UiSourceBundle';

export const NOT_VERIFIED_IN_GAME = 'Not verified in game' as const;

export type X4UiWorkspaceSourceStatus =
  | 'source-owned'
  | 'generated-shadowing-source'
  | 'unavailable'
  | 'locked';

export type X4UiWorkspaceSourceAvailability = 'available' | 'unavailable' | 'locked';

export type X4UiWorkspaceSourceReason =
  | 'source-owned'
  | 'no-root-ui-xml'
  | 'duplicate-root-ui-xml'
  | 'omitted-root-ui-xml'
  | 'no-registered-lua'
  | 'omitted-lua-source'
  | 'passthrough-lua-not-in-workspace'
  | 'ambiguous-passthrough-record'
  | 'malformed-xml'
  | 'malformed-lua'
  | 'missing-registered-lua'
  | 'duplicate-registered-lua'
  | 'ambiguous-registered-lua'
  | 'unsafe-source-path'
  | 'invalid-source-registration'
  | 'duplicate-supplied-lua'
  | 'source-bundle-failed'
  | 'generated-root-ui-xml'
  | 'generated-path-collision'
  | 'source-locked';

export type X4UiWorkspaceSourceCommitReason =
  | X4UiSourceSpliceRefusalReason
  | 'source-unavailable'
  | 'source-locked'
  | 'generated-shadowing-source'
  | 'concurrent-passthrough-change'
  | 'missing-passthrough-record'
  | 'stale-passthrough-path'
  | 'stale-passthrough-text'
  | 'source-projection-mismatch';

/** The input surface is intentionally the existing passthrough record shape. */
export interface X4UiWorkspaceSourceBuildOptions {
  /** Optional explicit Lua records. If omitted, every passthrough `.lua` record is used. */
  readonly passthroughLuaFiles?: readonly PassthroughFile[];
  /** Alias for callers already using the source-bundle vocabulary. */
  readonly luaFiles?: readonly PassthroughFile[];
  /** Exact UI paths known to be generated by the production package path. */
  readonly generatedPaths?: readonly string[];
}

export interface X4UiWorkspaceSourceRecord {
  readonly path: string;
  readonly content?: string;
  readonly reason?: PassthroughFile['reason'];
  readonly omitted?: boolean;
  readonly bytes?: number;
  readonly workspaceIndex: number | null;
  readonly bundleIndex?: number;
}

export interface X4UiWorkspaceSourceLuaBinding {
  readonly workspaceIndex: number | null;
  readonly bundleIndex?: number;
  readonly path: string;
  readonly expectedText?: string;
  readonly omitted: boolean;
}

export type X4UiWorkspaceSourceAuthority =
  | 'source-owned'
  | 'generated-shadowing-source'
  | 'unavailable';

export interface X4UiWorkspaceSourceCompileProjection {
  readonly authority: X4UiWorkspaceSourceAuthority;
  readonly uiCompileEnabled: boolean;
  readonly activeUiWidgets: boolean;
  readonly activeCustomLua: boolean;
  readonly generatedRootUiXml: boolean;
  readonly generatedPaths: readonly string[];
  /** Exact passthrough spellings that the generated manifest claims. */
  readonly generatedCollisions: readonly string[];
  /** Null unless the raw source is the package-visible authority. */
  readonly shippableProjection: X4UiSourceBundleProjection | null;
  readonly shippable: boolean;
}

export interface X4UiWorkspaceSourceCas {
  /** Frozen value snapshots; the caller workspace is never frozen. */
  readonly passthroughFiles: readonly X4UiWorkspaceSourceRecord[];
  readonly rootWorkspaceIndex: number | null;
  readonly luaBindings: readonly X4UiWorkspaceSourceLuaBinding[];
  /** Only the caller-supplied additions; the root path is derived from compile state. */
  readonly generatedPathInputs: readonly string[];
}

export interface X4UiWorkspaceSource {
  readonly status: X4UiWorkspaceSourceStatus;
  readonly availability: X4UiWorkspaceSourceAvailability;
  readonly available: boolean;
  readonly locked: boolean;
  readonly editable: boolean;
  readonly shippable: boolean;
  readonly reason: X4UiWorkspaceSourceReason;
  readonly reasons: readonly X4UiWorkspaceSourceReason[];
  readonly detail: string;
  readonly verification: typeof NOT_VERIFIED_IN_GAME;

  /** A unique usable root record; null means no unambiguous root authority. */
  readonly rootFile: X4UiWorkspaceSourceRecord | null;
  readonly rootCandidates: readonly X4UiWorkspaceSourceRecord[];
  /** Selected records retain workspace order, raw path spelling, and metadata. */
  readonly luaFiles: readonly X4UiWorkspaceSourceRecord[];
  readonly registeredLuaFiles: readonly X4UiWorkspaceSourceRecord[];

  /** Diagnostic materialization, including a locked or shadowed source when available. */
  readonly bundle: X4UiSourceBundle | null;
  readonly sourceBundle: X4UiSourceBundle | null;
  /** Only a source-owned bundle is exposed as package-shippable projection. */
  readonly projection: X4UiSourceBundleProjection | null;
  readonly compile: X4UiWorkspaceSourceCompileProjection;
  readonly cas: X4UiWorkspaceSourceCas;
}

export interface X4UiWorkspaceSourceSpliceResult {
  readonly accepted: boolean;
  readonly workspace: ModWorkspace;
  readonly source: X4UiWorkspaceSource;
  readonly bundle: X4UiSourceBundle | null;
  readonly reason: X4UiWorkspaceSourceCommitReason | null;
}

const issuedWorkspaceBySource = new WeakMap<X4UiWorkspaceSource, ModWorkspace>();

export function isIssuedX4UiWorkspaceSourcePair(workspace: unknown, source: unknown): boolean {
  if (source === null || (typeof source !== 'object' && typeof source !== 'function')) return false;
  return issuedWorkspaceBySource.get(source as X4UiWorkspaceSource) === workspace;
}

interface SelectedLuaRecord {
  readonly record: X4UiWorkspaceSourceRecord;
  readonly workspaceIndex: number | null;
  readonly mappingAmbiguous: boolean;
}

interface SourceBuildState {
  readonly workspaceFiles: readonly PassthroughFile[];
  readonly rootCandidates: readonly X4UiWorkspaceSourceRecord[];
  readonly rootFile: X4UiWorkspaceSourceRecord | null;
  readonly selectedLua: readonly SelectedLuaRecord[];
  readonly materializedLua: readonly {
    readonly selectedIndex: number;
    readonly bundleIndex: number;
    readonly record: X4UiWorkspaceSourceRecord;
  }[];
  readonly generatedPathInputs: readonly string[];
}

const hasOwn = (value: object, key: string): boolean => Object.prototype.hasOwnProperty.call(value, key);

function deepFreeze<T>(value: T, seen: WeakSet<object> = new WeakSet<object>()): T {
  if (value === null || typeof value !== 'object') return value;
  const objectValue = value as unknown as object;
  if (seen.has(objectValue)) return value;
  seen.add(objectValue);
  const record = value as unknown as Record<PropertyKey, unknown>;
  for (const key of Reflect.ownKeys(record)) {
    deepFreeze(record[key], seen);
  }
  return Object.freeze(value);
}

function freezeArray<T>(items: readonly T[]): readonly T[] {
  return Object.freeze([...items]);
}

function freezeObject<T extends object>(value: T): T {
  return Object.freeze(value);
}

function snapshotRecord(file: PassthroughFile): Omit<X4UiWorkspaceSourceRecord, 'workspaceIndex' | 'bundleIndex'> {
  return deepFreeze({
    path: file.path,
    ...(hasOwn(file, 'content') ? { content: file.content } : {}),
    ...(hasOwn(file, 'reason') ? { reason: file.reason } : {}),
    ...(hasOwn(file, 'omitted') ? { omitted: file.omitted } : {}),
    ...(hasOwn(file, 'bytes') ? { bytes: file.bytes } : {})
  });
}

function sameRecord(
  left: PassthroughFile | X4UiWorkspaceSourceRecord | undefined,
  right: PassthroughFile | X4UiWorkspaceSourceRecord | undefined
): boolean {
  if (!left || !right) return false;
  return left.path === right.path
    && left.content === right.content
    && left.reason === right.reason
    && left.omitted === right.omitted
    && left.bytes === right.bytes;
}

function sameRecordArray(
  current: readonly PassthroughFile[] | undefined,
  expected: readonly X4UiWorkspaceSourceRecord[]
): boolean {
  if (!Array.isArray(current) || current.length !== expected.length) return false;
  return expected.every((record, index) => sameRecord(current[index], record));
}

function normalizeManifestPath(path: string): string {
  return path.replace(/\\/g, '/').replace(/^\/+/, '').toLowerCase();
}

function isLuaPassthroughPath(path: string): boolean {
  return /\.lua$/i.test(path.replace(/\\/g, '/'));
}

function uniqueGeneratedPaths(paths: readonly string[]): readonly string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const path of paths) {
    if (typeof path !== 'string' || path.length === 0) continue;
    const key = normalizeManifestPath(path);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    result.push(path);
  }
  return freezeArray(result);
}

function activeUiWidgets(workspace: ModWorkspace): boolean {
  return Array.isArray(workspace.uiWidgets)
    && workspace.uiWidgets.some(widget => widget != null && widget.includeInBuild !== false);
}

function activeCustomLua(workspace: ModWorkspace): boolean {
  return typeof workspace.customLua === 'string' && workspace.customLua.trim().length > 0;
}

function compileFacts(
  workspace: ModWorkspace,
  generatedPathInputs: readonly string[],
  passthroughFiles: readonly PassthroughFile[]
): {
  readonly uiCompileEnabled: boolean;
  readonly activeUiWidgets: boolean;
  readonly activeCustomLua: boolean;
  readonly generatedRootUiXml: boolean;
  readonly generatedPaths: readonly string[];
  readonly generatedCollisions: readonly string[];
} {
  const uiCompileEnabled = workspace.compileSettings?.ui !== false;
  const widgets = activeUiWidgets(workspace);
  const customLua = activeCustomLua(workspace);
  const generatedRootUiXml = uiCompileEnabled && (widgets || customLua);
  const generatedPaths = uniqueGeneratedPaths([
    ...(generatedRootUiXml ? ['ui.xml'] : []),
    ...(uiCompileEnabled ? generatedPathInputs : [])
  ]);
  const generatedKeys = new Set(generatedPaths.map(normalizeManifestPath));
  const generatedCollisions = passthroughFiles
    .filter(file => generatedKeys.has(normalizeManifestPath(file.path)))
    .map(file => file.path);

  return {
    uiCompileEnabled,
    activeUiWidgets: widgets,
    activeCustomLua: customLua,
    generatedRootUiXml,
    generatedPaths,
    generatedCollisions: freezeArray(generatedCollisions)
  };
}

function findRecordMatches(files: readonly PassthroughFile[], target: PassthroughFile): readonly number[] {
  const identityMatches = files
    .map((file, index) => file === target ? index : -1)
    .filter(index => index >= 0);
  if (identityMatches.length > 0) return freezeArray(identityMatches);
  return freezeArray(files
    .map((file, index) => sameRecord(file, target) ? index : -1)
    .filter(index => index >= 0));
}

function makeWorkspaceRecord(
  file: PassthroughFile,
  workspaceIndex: number | null,
  bundleIndex?: number
): X4UiWorkspaceSourceRecord {
  return deepFreeze({
    ...snapshotRecord(file),
    workspaceIndex,
    ...(bundleIndex === undefined ? {} : { bundleIndex })
  });
}

function selectedLuaRecords(
  workspaceFiles: readonly PassthroughFile[],
  options: X4UiWorkspaceSourceBuildOptions
): readonly SelectedLuaRecord[] {
  const explicit = options.passthroughLuaFiles ?? options.luaFiles;
  const records = explicit === undefined
    ? workspaceFiles.filter(file => typeof file.path === 'string' && isLuaPassthroughPath(file.path))
    : explicit;

  return freezeArray(records.map(record => {
    const matches = findRecordMatches(workspaceFiles, record);
    const workspaceIndex = matches.length === 1 ? matches[0] : null;
    return {
      record: makeWorkspaceRecord(record, workspaceIndex),
      workspaceIndex,
      mappingAmbiguous: matches.length > 1
    };
  }));
}

function buildState(
  workspace: ModWorkspace,
  options: X4UiWorkspaceSourceBuildOptions
): SourceBuildState {
  const workspaceFiles = Array.isArray(workspace.passthroughFiles)
    ? workspace.passthroughFiles
    : [];
  const rootIndexes = workspaceFiles
    .map((file, index) => typeof file?.path === 'string' && file.path.toLowerCase() === 'ui.xml' ? index : -1)
    .filter(index => index >= 0);
  const rootCandidates = freezeArray(rootIndexes.map(index => makeWorkspaceRecord(workspaceFiles[index], index)));
  const rootFile = rootCandidates.length === 1 ? rootCandidates[0] : null;
  const selectedLua = selectedLuaRecords(workspaceFiles, options);
  const materializedLua: {
    readonly selectedIndex: number;
    readonly bundleIndex: number;
    readonly record: X4UiWorkspaceSourceRecord;
  }[] = [];
  for (let selectedIndex = 0; selectedIndex < selectedLua.length; selectedIndex += 1) {
    const selected = selectedLua[selectedIndex];
    if (selected.record.omitted === true || typeof selected.record.content !== 'string') continue;
    materializedLua.push({
      selectedIndex,
      bundleIndex: materializedLua.length,
      record: makeWorkspaceRecord(selected.record, selected.workspaceIndex, materializedLua.length)
    });
  }

  const suppliedPaths = options.generatedPaths === undefined
    ? []
    : options.generatedPaths.filter(path => typeof path === 'string');

  return {
    workspaceFiles,
    rootCandidates,
    rootFile,
    selectedLua,
    materializedLua: freezeArray(materializedLua),
    generatedPathInputs: freezeArray(suppliedPaths)
  };
}

function addReason(
  reasons: X4UiWorkspaceSourceReason[],
  reason: X4UiWorkspaceSourceReason
): void {
  if (!reasons.includes(reason)) reasons.push(reason);
}

function bundleReasons(
  bundle: X4UiSourceBundle,
  state: SourceBuildState
): X4UiWorkspaceSourceReason[] {
  const reasons: X4UiWorkspaceSourceReason[] = [];
  if (!bundle.xml.parsed) addReason(reasons, 'malformed-xml');
  if (bundle.registrations.length === 0) addReason(reasons, 'no-registered-lua');

  for (const registration of bundle.registrations) {
    switch (registration.resolution) {
      case 'missing-file':
        addReason(reasons, 'missing-registered-lua');
        break;
      case 'duplicate-registration':
        addReason(reasons, 'duplicate-registered-lua');
        break;
      case 'ambiguous-source-file':
        addReason(reasons, 'ambiguous-registered-lua');
        break;
      case 'unsafe-traversal':
      case 'unsafe-absolute':
        addReason(reasons, 'unsafe-source-path');
        break;
      case 'missing-name':
      case 'invalid-path':
        addReason(reasons, 'invalid-source-registration');
        break;
      case 'malformed-xml':
        addReason(reasons, 'malformed-xml');
        break;
      case 'resolved':
        break;
    }
  }

  for (const diagnostic of bundle.diagnostics) {
    switch (diagnostic.code) {
      case 'lua-parse-failure':
        addReason(reasons, 'malformed-lua');
        break;
      case 'unsafe-lua-file':
        addReason(reasons, 'unsafe-source-path');
        break;
      case 'duplicate-supplied-lua-file':
        addReason(reasons, 'duplicate-supplied-lua');
        break;
      default:
        break;
    }
  }

  if (state.selectedLua.some(selected => selected.record.omitted === true || selected.record.content === undefined)) {
    addReason(reasons, 'omitted-lua-source');
  }
  if (state.selectedLua.some(selected => selected.mappingAmbiguous)) {
    addReason(reasons, 'ambiguous-passthrough-record');
  }
  if (state.selectedLua.some(selected => selected.workspaceIndex === null)) {
    addReason(reasons, 'passthrough-lua-not-in-workspace');
  }
  if (bundle.locked && reasons.length === 0) addReason(reasons, 'source-locked');
  return reasons;
}

function sourceDetail(status: X4UiWorkspaceSourceStatus, reason: X4UiWorkspaceSourceReason): string {
  switch (status) {
    case 'source-owned':
      return 'The accepted source bundle is the package-visible UI authority.';
    case 'generated-shadowing-source':
      return reason === 'generated-path-collision'
        ? 'Generated UI output claims a passthrough path; the generated file wins.'
        : 'Generated root ui.xml claims the passthrough menu; the generated manifest wins.';
    case 'unavailable':
      return reason === 'no-root-ui-xml'
        ? 'No exact extension-root ui.xml passthrough record was supplied.'
        : 'The workspace has no unambiguous usable root UI source record.';
    case 'locked':
      return 'The source bundle is present but locked by an explicit source or registration condition.';
  }
}

function compileProjection(
  status: X4UiWorkspaceSourceStatus,
  workspace: ModWorkspace,
  state: SourceBuildState,
  bundle: X4UiSourceBundle | null,
  projection: X4UiSourceBundleProjection | null
): X4UiWorkspaceSourceCompileProjection {
  const facts = compileFacts(workspace, state.generatedPathInputs, state.workspaceFiles);
  const authority: X4UiWorkspaceSourceAuthority = status === 'source-owned'
    ? 'source-owned'
    : status === 'generated-shadowing-source'
      ? 'generated-shadowing-source'
      : 'unavailable';
  const shippableProjection = status === 'source-owned' && bundle && projection ? projection : null;
  return deepFreeze({
    authority,
    uiCompileEnabled: facts.uiCompileEnabled,
    activeUiWidgets: facts.activeUiWidgets,
    activeCustomLua: facts.activeCustomLua,
    generatedRootUiXml: facts.generatedRootUiXml,
    generatedPaths: facts.generatedPaths,
    generatedCollisions: facts.generatedCollisions,
    shippableProjection,
    shippable: shippableProjection !== null
  });
}

/**
 * Build a frozen, filesystem-free source projection from existing workspace
 * passthrough records.  All XML/Lua interpretation remains owned by the
 * accepted x4UiSourceBundle module.
 */
export function buildX4UiWorkspaceSource(
  workspace: ModWorkspace,
  optionsOrLuaFiles: X4UiWorkspaceSourceBuildOptions | readonly PassthroughFile[] = {}
): X4UiWorkspaceSource {
  const options: X4UiWorkspaceSourceBuildOptions = Array.isArray(optionsOrLuaFiles)
    ? { passthroughLuaFiles: optionsOrLuaFiles as readonly PassthroughFile[] }
    : optionsOrLuaFiles as X4UiWorkspaceSourceBuildOptions;
  const state = buildState(workspace, options);
  const snapshot = freezeArray(state.workspaceFiles.map((file, index) => makeWorkspaceRecord(file, index)));
  const casLuaBindings: X4UiWorkspaceSourceLuaBinding[] = state.selectedLua.map((selected, selectedIndex) => {
    const materialized = state.materializedLua.find(item => item.selectedIndex === selectedIndex);
    return deepFreeze({
      workspaceIndex: selected.workspaceIndex,
      ...(materialized === undefined ? {} : { bundleIndex: materialized.bundleIndex }),
      path: selected.record.path,
      ...(selected.record.content === undefined ? {} : { expectedText: selected.record.content }),
      omitted: selected.record.omitted === true || selected.record.content === undefined
    });
  });

  const rootUsable = state.rootFile !== null
    && state.rootFile.omitted !== true
    && typeof state.rootFile.content === 'string';
  let bundle: X4UiSourceBundle | null = null;
  let projection: X4UiSourceBundleProjection | null = null;
  let buildFailure = false;
  if (rootUsable) {
    try {
      bundle = deepFreeze(buildX4UiSourceBundle({
        uiXml: state.rootFile.content as string,
        luaFiles: state.materializedLua.map(item => ({
          path: item.record.path,
          text: item.record.content as string
        }))
      }));
      projection = deepFreeze(projectX4UiSourceBundle(bundle));
    } catch {
      buildFailure = true;
    }
  }

  const reasons: X4UiWorkspaceSourceReason[] = [];
  if (state.rootCandidates.length === 0) {
    addReason(reasons, 'no-root-ui-xml');
  } else if (state.rootCandidates.length > 1) {
    addReason(reasons, 'duplicate-root-ui-xml');
  } else if (!rootUsable) {
    addReason(reasons, 'omitted-root-ui-xml');
  }
  if (buildFailure) addReason(reasons, 'source-bundle-failed');
  if (bundle) {
    for (const reason of bundleReasons(bundle, state)) addReason(reasons, reason);
  } else if (rootUsable && !buildFailure) {
    addReason(reasons, 'source-bundle-failed');
  }

  const facts = compileFacts(workspace, state.generatedPathInputs, state.workspaceFiles);
  const canShadow = state.rootCandidates.length === 1 && rootUsable;
  const generatedShadow = canShadow && (facts.generatedRootUiXml || facts.generatedCollisions.length > 0);
  if (generatedShadow) {
    addReason(reasons, facts.generatedRootUiXml ? 'generated-root-ui-xml' : 'generated-path-collision');
  }

  const structurallyLocked = reasons.some(reason => reason !== 'generated-root-ui-xml' && reason !== 'generated-path-collision');
  let status: X4UiWorkspaceSourceStatus;
  if (!canShadow && (state.rootCandidates.length === 0 || state.rootCandidates.length > 1 || !rootUsable)) {
    status = 'unavailable';
  } else if (generatedShadow) {
    status = 'generated-shadowing-source';
  } else if (structurallyLocked || bundle === null || projection === null) {
    status = 'locked';
  } else {
    status = 'source-owned';
  }

  const primaryReason = status === 'source-owned'
    ? 'source-owned'
    : status === 'generated-shadowing-source'
      ? (facts.generatedRootUiXml ? 'generated-root-ui-xml' : 'generated-path-collision')
      : reasons[0] || 'source-locked';
  if (status === 'source-owned') reasons.splice(0, reasons.length, 'source-owned');
  const sourceProjection = status === 'source-owned' ? projection : null;
  const editable = status === 'source-owned'
    && bundle !== null
    && bundle.sourceFiles.length > 0
    && bundle.sourceFiles
      .filter(file => file.registered)
      .every(file => file.editable);
  const registeredLuaFiles = bundle === null
    ? []
    : bundle.orderedFiles
      .map(file => state.materializedLua.find(item => item.bundleIndex === file.index))
      .filter((item): item is (typeof state.materializedLua)[number] => item !== undefined)
      .map(item => item.record);
  const compile = compileProjection(status, workspace, state, bundle, sourceProjection);
  const cas: X4UiWorkspaceSourceCas = deepFreeze({
    passthroughFiles: snapshot,
    rootWorkspaceIndex: state.rootFile?.workspaceIndex ?? null,
    luaBindings: freezeArray(casLuaBindings),
    generatedPathInputs: state.generatedPathInputs
  });

  const emittedSource: X4UiWorkspaceSource = deepFreeze({
    status,
    availability: status === 'source-owned' ? 'available' : status === 'unavailable' ? 'unavailable' : 'locked',
    available: status === 'source-owned',
    locked: status === 'locked' || status === 'generated-shadowing-source',
    editable,
    shippable: sourceProjection !== null,
    reason: primaryReason,
    reasons: freezeArray(reasons),
    detail: sourceDetail(status, primaryReason),
    verification: NOT_VERIFIED_IN_GAME,
    rootFile: state.rootFile,
    rootCandidates: state.rootCandidates,
    luaFiles: freezeArray(state.selectedLua.map(selected => selected.record)),
    registeredLuaFiles: freezeArray(registeredLuaFiles),
    bundle,
    sourceBundle: bundle,
    projection: sourceProjection,
    compile,
    cas
  });
  issuedWorkspaceBySource.set(emittedSource, workspace);
  return emittedSource;
}

export const inspectX4UiWorkspaceSource = buildX4UiWorkspaceSource;

function refusal(
  workspace: ModWorkspace,
  source: X4UiWorkspaceSource,
  reason: X4UiWorkspaceSourceCommitReason,
  bundle: X4UiSourceBundle | null = source.bundle
): X4UiWorkspaceSourceSpliceResult {
  return freezeObject({ accepted: false, workspace, source, bundle, reason });
}

function currentCompileShadowed(
  workspace: ModWorkspace,
  source: X4UiWorkspaceSource
): boolean {
  const currentFiles = Array.isArray(workspace.passthroughFiles) ? workspace.passthroughFiles : [];
  const facts = compileFacts(workspace, source.cas.generatedPathInputs, currentFiles);
  return facts.generatedRootUiXml || facts.generatedCollisions.length > 0;
}

/**
 * Apply the source-bundle CAS first, then commit only when the complete
 * passthrough snapshot and every source path/index/text precondition still
 * match the workspace supplied at commit time.
 */
export function spliceX4UiWorkspaceSource(
  workspace: ModWorkspace,
  source: X4UiWorkspaceSource,
  edit: X4UiSourceSplice
): X4UiWorkspaceSourceSpliceResult {
  if (source.status === 'generated-shadowing-source') {
    return refusal(workspace, source, 'generated-shadowing-source');
  }
  if (source.status === 'unavailable') return refusal(workspace, source, 'source-unavailable');
  if (source.status !== 'source-owned' || source.bundle === null || source.projection === null) {
    return refusal(workspace, source, 'source-locked');
  }

  const splice = spliceX4UiSourceBundle(source.bundle, edit);
  if (!splice.accepted) return refusal(workspace, source, splice.reason as X4UiSourceSpliceRefusalReason);

  const currentFiles = Array.isArray(workspace.passthroughFiles) ? workspace.passthroughFiles : undefined;
  if (!sameRecordArray(currentFiles, source.cas.passthroughFiles)) {
    return refusal(workspace, source, 'concurrent-passthrough-change', splice.bundle);
  }
  if (currentCompileShadowed(workspace, source)) {
    return refusal(workspace, source, 'generated-shadowing-source', splice.bundle);
  }

  const before = source.projection;
  const after = projectX4UiSourceBundle(splice.bundle);
  if (after.uiXml !== before.uiXml || after.luaFiles.length !== before.luaFiles.length) {
    return refusal(workspace, source, 'source-projection-mismatch', splice.bundle);
  }

  const nextFiles = currentFiles ? [...currentFiles] : [];
  const changedIndexes = new Set<number>();
  for (const binding of source.cas.luaBindings) {
    if (binding.workspaceIndex === null || binding.bundleIndex === undefined) {
      return refusal(workspace, source, 'missing-passthrough-record', splice.bundle);
    }
    const current = currentFiles?.[binding.workspaceIndex];
    const expected = source.cas.passthroughFiles[binding.workspaceIndex];
    const beforeFile = before.luaFiles[binding.bundleIndex];
    const afterFile = after.luaFiles[binding.bundleIndex];
    if (!current || !expected || !beforeFile || !afterFile) {
      return refusal(workspace, source, 'missing-passthrough-record', splice.bundle);
    }
    if (current.path !== expected.path || current.path !== beforeFile.path || afterFile.path !== current.path) {
      return refusal(workspace, source, 'stale-passthrough-path', splice.bundle);
    }
    if (current.content !== expected.content || current.content !== beforeFile.text) {
      return refusal(workspace, source, 'stale-passthrough-text', splice.bundle);
    }
    if (afterFile.text !== beforeFile.text) {
      nextFiles[binding.workspaceIndex] = { ...current, content: afterFile.text };
      changedIndexes.add(binding.workspaceIndex);
    }
  }

  const nextWorkspace = changedIndexes.size === 0
    ? workspace
    : { ...workspace, passthroughFiles: nextFiles };
  const nextLuaRecords = source.luaFiles.map(file => {
    if (file.workspaceIndex === null) return file;
    return nextFiles[file.workspaceIndex] || file;
  });
  const nextSource = buildX4UiWorkspaceSource(nextWorkspace, {
    passthroughLuaFiles: nextLuaRecords,
    generatedPaths: source.cas.generatedPathInputs
  });
  return freezeObject({
    accepted: true,
    workspace: nextWorkspace,
    source: nextSource,
    bundle: splice.bundle,
    reason: null
  });
}

export const commitX4UiWorkspaceSourceSplice = spliceX4UiWorkspaceSource;
export const applyX4UiWorkspaceSourceSplice = spliceX4UiWorkspaceSource;
